name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Create env file'
      run: |
        touch .env
        echo DB_CONNECTION_STRING=${{ secrets.MONGO_CONNECT_STR }} >> .env
        echo PORT=${{ PORT }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
        echo ".env file created"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
